# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51e974c36b6e761a86b0fc72d149be27e2901fce01447bda42e57a38f697da10756d38c04f8e76e5d84ce6ca0afaac4b2bb60fe25c790a5ca19227e1419464be

test:
  secret_key_base: 390a37e8ccb43e67aef7abd890f7bf8f2357d48b2d17d5a0f905e702aa4ecd98592ac26bd56ff59473552b1ca0f6d2fa8927d08124718f1d33d7d427e80dbf7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
